#!/bin/bash

# Quick Firestore Data Check
echo "🔍 Checking if there's any data in Firestore..."
echo ""

# This will help you manually check
echo "Manual Check Required:"
echo ""
echo "1. Go to Firebase Console:"
echo "   https://console.firebase.google.com/project/smartstyle-c8276/firestore/data"
echo ""
echo "2. Look for this path:"
echo "   users → [your-user-id] → likedOutfits"
echo ""
echo "3. Your user ID should be visible in the browser console when signed in:"
echo "   console.log(auth.currentUser?.uid)"
echo ""
echo "---"
echo ""
echo "If you see documents there:"
echo "  ✅ Data is saved correctly"
echo "  → The issue is with fetching/displaying"
echo ""
echo "If you DON'T see documents:"
echo "  ❌ Data is not being saved"
echo "  → The issue is with the save function"
echo ""
echo "Run the browser diagnostic for detailed analysis:"
echo "  Open app → F12 → Console → Paste diagnose-likes.js content"
echo ""
